"""Add state fields to blogpost

Revision ID: 2bbb0d37989a
Revises: 13ea3a4b5a2f
Create Date: 2022-08-16 17:59:44.382443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bbb0d37989a'
down_revision = '13ea3a4b5a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BlogPost',
        sa.Column('is_draft', sa.Boolean(), nullable=False)
    )
    op.add_column('BlogPost',
        sa.Column('created_date', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BlogPost', 'is_draft')
    op.drop_column('BlogPost', 'created_date')
    # ### end Alembic commands ###
