"""increase size of image column

Revision ID: 2cb8e64d54e2
Revises: 4dd85d3b2581
Create Date: 2022-12-16 17:05:02.747097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2cb8e64d54e2'
down_revision = '4dd85d3b2581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('BlogPost', 'image',
               existing_type=mysql.MEDIUMTEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('BlogPost', 'image',
               existing_type=sa.Text(5000),
               nullable=True)
    # ### end Alembic commands ###
